#!/bin/bash

NAME="predictor"
VERSION="1.0"
SCALA_VERSION="2.11"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
JAR="$DIR/target/scala-$SCALA_VERSION/$NAME-assembly-$VERSION.jar"

ACTION=$1
OWNER=$2
REPOSITORY=$3

if ! [ -f "$JAR" ]; then
  echo "JAR file does not exist." >&2
  echo "Make sure you run \`sbt assembly\` to build the JAR executable." >&2
  exit 1
fi

if [ "$#" -ne 3 ]; then
  echo "Wrong number of arguments, expected 3 arguments." >&2
  echo "Usage: $0 action owner_name repository_name" >&2
  exit 1
fi

case "$OWNER$REPOSITORY" in
  *\ * )
  echo "Whitespace is not supported." >&2
  exit 1
  ;;
esac

JAVA_OPTS="-Dfile.encoding=UTF8 -Drepository.owner=$OWNER -Drepository.name=$REPOSITORY"
java $JAVA_OPTS -jar $JAR $ACTION
